#!/bin/bash

subdir=src/main/java/org/lsc/configuration

find $subdir -name '*.java'  | xargs grep -l -e '\(Généré le\)\|\(Generated on\)' | {
    while read file; do git rm  --cached $file ; done
}

pushd $subdir
{
    echo "# ignore autogenerated java files"
    find -name '*.java'  | xargs grep -l -e '\(Généré le\)\|\(Generated on\)' | sed 's/^\.\/\(.*\)$/\/\1/'
} > .gitignore

      
popd
