//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.17 at 11:12:33 PM CEST 
//


package org.lsc.configuration;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for asyncLdapSourceServiceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="asyncLdapSourceServiceType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://lsc-project.org/XSD/lsc-core-2.0.xsd}ldapSourceServiceType">
 *       &lt;sequence>
 *         &lt;element name="synchronizingAllWhenStarting" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="serverType" type="{http://lsc-project.org/XSD/lsc-core-2.0.xsd}ldapServerType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "asyncLdapSourceServiceType", propOrder = {
    "synchronizingAllWhenStarting",
    "serverType"
})
public class AsyncLdapSourceServiceType
    extends LdapSourceServiceType
{

    @XmlElement(defaultValue = "true")
    protected Boolean synchronizingAllWhenStarting = true;
    @XmlElement(required = true)
    protected LdapServerType serverType;

    /**
     * Gets the value of the synchronizingAllWhenStarting property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSynchronizingAllWhenStarting() {
        return synchronizingAllWhenStarting;
    }

    /**
     * Sets the value of the synchronizingAllWhenStarting property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSynchronizingAllWhenStarting(Boolean value) {
        this.synchronizingAllWhenStarting = value;
    }

    /**
     * Gets the value of the serverType property.
     * 
     * @return
     *     possible object is
     *     {@link LdapServerType }
     *     
     */
    public LdapServerType getServerType() {
        return serverType;
    }

    /**
     * Sets the value of the serverType property.
     * 
     * @param value
     *     allowed object is
     *     {@link LdapServerType }
     *     
     */
    public void setServerType(LdapServerType value) {
        this.serverType = value;
    }

}
