//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.23 at 07:48:47 PM CET 
//


package org.lsc.configuration;

import java.util.ArrayList;
import java.util.List;
import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for connectionsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="connectionsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element name="ldapConnection" type="{http://lsc-project.org/XSD/lsc-core-2.0.xsd}ldapConnectionType" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element name="databaseConnection" type="{http://lsc-project.org/XSD/lsc-core-2.0.xsd}databaseConnectionType" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element name="nisConnection" type="{http://lsc-project.org/XSD/lsc-core-2.0.xsd}nisConnectionType" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element name="pluginConnection" type="{http://lsc-project.org/XSD/lsc-core-2.0.xsd}pluginConnectionType"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "connectionsType", namespace = "http://lsc-project.org/XSD/lsc-core-2.0.xsd", propOrder = {
    "ldapConnectionOrDatabaseConnectionOrNisConnection"
})
@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-01-23T07:48:47+01:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
public class ConnectionsType {

    @XmlElements({
        @XmlElement(name = "ldapConnection", namespace = "http://lsc-project.org/XSD/lsc-core-2.0.xsd", type = LdapConnectionType.class),
        @XmlElement(name = "pluginConnection", namespace = "http://lsc-project.org/XSD/lsc-core-2.0.xsd", type = PluginConnectionType.class),
        @XmlElement(name = "databaseConnection", namespace = "http://lsc-project.org/XSD/lsc-core-2.0.xsd", type = DatabaseConnectionType.class),
        @XmlElement(name = "nisConnection", namespace = "http://lsc-project.org/XSD/lsc-core-2.0.xsd", type = NisConnectionType.class)
    })
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-01-23T07:48:47+01:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    protected List<ConnectionType> ldapConnectionOrDatabaseConnectionOrNisConnection;
    @XmlAttribute
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-01-23T07:48:47+01:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    protected String id;

    /**
     * Gets the value of the ldapConnectionOrDatabaseConnectionOrNisConnection property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ldapConnectionOrDatabaseConnectionOrNisConnection property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLdapConnectionOrDatabaseConnectionOrNisConnection().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LdapConnectionType }
     * {@link PluginConnectionType }
     * {@link DatabaseConnectionType }
     * {@link NisConnectionType }
     * 
     * 
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-01-23T07:48:47+01:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    public List<ConnectionType> getLdapConnectionOrDatabaseConnectionOrNisConnection() {
        if (ldapConnectionOrDatabaseConnectionOrNisConnection == null) {
            ldapConnectionOrDatabaseConnectionOrNisConnection = new ArrayList<ConnectionType>();
        }
        return this.ldapConnectionOrDatabaseConnectionOrNisConnection;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-01-23T07:48:47+01:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-01-23T07:48:47+01:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    public void setId(String value) {
        this.id = value;
    }

}
