//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.16 at 12:06:23 AM CET 
//


package org.lsc.configuration;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ldapServerType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ldapServerType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="OpenLDAP"/>
 *     &lt;enumeration value="ApacheDS"/>
 *     &lt;enumeration value="OpenDS"/>
 *     &lt;enumeration value="OpenDJ"/>
 *     &lt;enumeration value="OracleDS"/>
 *     &lt;enumeration value="SunDS"/>
 *     &lt;enumeration value="NetscapeDS"/>
 *     &lt;enumeration value="ActiveDirectory"/>
 *     &lt;enumeration value="NovellEDirectory"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ldapServerType", namespace = "http://lsc-project.org/XSD/lsc-core-2.0.xsd")
@XmlEnum
public enum LdapServerType {

    @XmlEnumValue("OpenLDAP")
    OPEN_LDAP("OpenLDAP"),
    @XmlEnumValue("ApacheDS")
    APACHE_DS("ApacheDS"),
    @XmlEnumValue("OpenDS")
    OPEN_DS("OpenDS"),
    @XmlEnumValue("OpenDJ")
    OPEN_DJ("OpenDJ"),
    @XmlEnumValue("OracleDS")
    ORACLE_DS("OracleDS"),
    @XmlEnumValue("SunDS")
    SUN_DS("SunDS"),
    @XmlEnumValue("NetscapeDS")
    NETSCAPE_DS("NetscapeDS"),
    @XmlEnumValue("ActiveDirectory")
    ACTIVE_DIRECTORY("ActiveDirectory"),
    @XmlEnumValue("NovellEDirectory")
    NOVELL_E_DIRECTORY("NovellEDirectory");
    private final String value;

    LdapServerType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static LdapServerType fromValue(String v) {
        for (LdapServerType c: LdapServerType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
