//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.23 at 07:48:47 PM CET 
//


package org.lsc.configuration;

import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ldapAuthenticationType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ldapAuthenticationType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="NONE"/>
 *     &lt;enumeration value="SIMPLE"/>
 *     &lt;enumeration value="SASL"/>
 *     &lt;enumeration value="DIGEST-MD5"/>
 *     &lt;enumeration value="GSSAPI"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ldapAuthenticationType", namespace = "http://lsc-project.org/XSD/lsc-core-2.0.xsd")
@XmlEnum
@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-01-23T07:48:47+01:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
public enum LdapAuthenticationType {

    NONE("NONE"),
    SIMPLE("SIMPLE"),
    SASL("SASL"),
    @XmlEnumValue("DIGEST-MD5")
    DIGEST_MD_5("DIGEST-MD5"),
    GSSAPI("GSSAPI");
    private final String value;

    LdapAuthenticationType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static LdapAuthenticationType fromValue(String v) {
        for (LdapAuthenticationType c: LdapAuthenticationType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
