//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.16 at 07:22:18 PM CEST 
//


package org.lsc.configuration;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.lsc.configuration package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.lsc.configuration
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ServiceType }
     * 
     */
    public ServiceType createServiceType() {
        return new ServiceType();
    }

    /**
     * Create an instance of {@link MultiDestinationServiceType }
     * 
     */
    public MultiDestinationServiceType createMultiDestinationServiceType() {
        return new MultiDestinationServiceType();
    }

    /**
     * Create an instance of {@link TaskType }
     * 
     */
    public TaskType createTaskType() {
        return new TaskType();
    }

    /**
     * Create an instance of {@link KeysValuesMap }
     * 
     */
    public KeysValuesMap createKeysValuesMap() {
        return new KeysValuesMap();
    }

    /**
     * Create an instance of {@link Lsc }
     * 
     */
    public Lsc createLsc() {
        return new Lsc();
    }

    /**
     * Create an instance of {@link ConnectionsType }
     * 
     */
    public ConnectionsType createConnectionsType() {
        return new ConnectionsType();
    }

    /**
     * Create an instance of {@link AuditsType }
     * 
     */
    public AuditsType createAuditsType() {
        return new AuditsType();
    }

    /**
     * Create an instance of {@link TasksType }
     * 
     */
    public TasksType createTasksType() {
        return new TasksType();
    }

    /**
     * Create an instance of {@link SecurityType }
     * 
     */
    public SecurityType createSecurityType() {
        return new SecurityType();
    }

    /**
     * Create an instance of {@link PluginSyncOptionsType }
     * 
     */
    public PluginSyncOptionsType createPluginSyncOptionsType() {
        return new PluginSyncOptionsType();
    }

    /**
     * Create an instance of {@link GoogleAppsConnectionType }
     * 
     */
    public GoogleAppsConnectionType createGoogleAppsConnectionType() {
        return new GoogleAppsConnectionType();
    }

    /**
     * Create an instance of {@link PluginConnectionType }
     * 
     */
    public PluginConnectionType createPluginConnectionType() {
        return new PluginConnectionType();
    }

    /**
     * Create an instance of {@link EncryptionType }
     * 
     */
    public EncryptionType createEncryptionType() {
        return new EncryptionType();
    }

    /**
     * Create an instance of {@link AuditType }
     * 
     */
    public AuditType createAuditType() {
        return new AuditType();
    }

    /**
     * Create an instance of {@link LdifAuditType }
     * 
     */
    public LdifAuditType createLdifAuditType() {
        return new LdifAuditType();
    }

    /**
     * Create an instance of {@link ConnectionType }
     * 
     */
    public ConnectionType createConnectionType() {
        return new ConnectionType();
    }

    /**
     * Create an instance of {@link PluginSourceServiceType }
     * 
     */
    public PluginSourceServiceType createPluginSourceServiceType() {
        return new PluginSourceServiceType();
    }

    /**
     * Create an instance of {@link XaFileDestinationServiceType }
     * 
     */
    public XaFileDestinationServiceType createXaFileDestinationServiceType() {
        return new XaFileDestinationServiceType();
    }

    /**
     * Create an instance of {@link PluginDestinationServiceType }
     * 
     */
    public PluginDestinationServiceType createPluginDestinationServiceType() {
        return new PluginDestinationServiceType();
    }

    /**
     * Create an instance of {@link ConditionsType }
     * 
     */
    public ConditionsType createConditionsType() {
        return new ConditionsType();
    }

    /**
     * Create an instance of {@link DatabaseSourceServiceType }
     * 
     */
    public DatabaseSourceServiceType createDatabaseSourceServiceType() {
        return new DatabaseSourceServiceType();
    }

    /**
     * Create an instance of {@link GoogleAppsServiceType }
     * 
     */
    public GoogleAppsServiceType createGoogleAppsServiceType() {
        return new GoogleAppsServiceType();
    }

    /**
     * Create an instance of {@link AsyncLdapSourceServiceType }
     * 
     */
    public AsyncLdapSourceServiceType createAsyncLdapSourceServiceType() {
        return new AsyncLdapSourceServiceType();
    }

    /**
     * Create an instance of {@link LdapConnectionType }
     * 
     */
    public LdapConnectionType createLdapConnectionType() {
        return new LdapConnectionType();
    }

    /**
     * Create an instance of {@link DatasetType }
     * 
     */
    public DatasetType createDatasetType() {
        return new DatasetType();
    }

    /**
     * Create an instance of {@link LdapDestinationServiceType }
     * 
     */
    public LdapDestinationServiceType createLdapDestinationServiceType() {
        return new LdapDestinationServiceType();
    }

    /**
     * Create an instance of {@link PropertiesBasedSyncOptionsType }
     * 
     */
    public PropertiesBasedSyncOptionsType createPropertiesBasedSyncOptionsType() {
        return new PropertiesBasedSyncOptionsType();
    }

    /**
     * Create an instance of {@link ValuesType }
     * 
     */
    public ValuesType createValuesType() {
        return new ValuesType();
    }

    /**
     * Create an instance of {@link ForceSyncOptionsType }
     * 
     */
    public ForceSyncOptionsType createForceSyncOptionsType() {
        return new ForceSyncOptionsType();
    }

    /**
     * Create an instance of {@link DatabaseConnectionType }
     * 
     */
    public DatabaseConnectionType createDatabaseConnectionType() {
        return new DatabaseConnectionType();
    }

    /**
     * Create an instance of {@link LdapSourceServiceType }
     * 
     */
    public LdapSourceServiceType createLdapSourceServiceType() {
        return new LdapSourceServiceType();
    }

    /**
     * Create an instance of {@link PluginAuditType }
     * 
     */
    public PluginAuditType createPluginAuditType() {
        return new PluginAuditType();
    }

    /**
     * Create an instance of {@link CsvAuditType }
     * 
     */
    public CsvAuditType createCsvAuditType() {
        return new CsvAuditType();
    }

    /**
     * Create an instance of {@link DatabaseDestinationServiceType }
     * 
     */
    public DatabaseDestinationServiceType createDatabaseDestinationServiceType() {
        return new DatabaseDestinationServiceType();
    }

    /**
     * Create an instance of {@link ServiceType.Connection }
     * 
     */
    public ServiceType.Connection createServiceTypeConnection() {
        return new ServiceType.Connection();
    }

    /**
     * Create an instance of {@link MultiDestinationServiceType.XaServices }
     * 
     */
    public MultiDestinationServiceType.XaServices createMultiDestinationServiceTypeXaServices() {
        return new MultiDestinationServiceType.XaServices();
    }

    /**
     * Create an instance of {@link TaskType.AuditLog }
     * 
     */
    public TaskType.AuditLog createTaskTypeAuditLog() {
        return new TaskType.AuditLog();
    }

    /**
     * Create an instance of {@link KeysValuesMap.Entry }
     * 
     */
    public KeysValuesMap.Entry createKeysValuesMapEntry() {
        return new KeysValuesMap.Entry();
    }

}
