//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.15 at 10:37:30 AM CEST 
//


package org.lsc.configuration;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for pivotTransformationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="pivotTransformationType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="transformation" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                 &lt;attribute name="fromAttribute" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="toAttribute" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="pivotOrigin" type="{http://lsc-project.org/XSD/lsc-core-2.2.xsd}pivotOriginType" default="BOTH" /&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "pivotTransformationType", propOrder = {
    "transformation"
})
public class PivotTransformationType {

    protected List<PivotTransformationType.Transformation> transformation;

    /**
     * Gets the value of the transformation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the transformation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTransformation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PivotTransformationType.Transformation }
     * 
     * 
     */
    public List<PivotTransformationType.Transformation> getTransformation() {
        if (transformation == null) {
            transformation = new ArrayList<PivotTransformationType.Transformation>();
        }
        return this.transformation;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;simpleContent&gt;
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
     *       &lt;attribute name="fromAttribute" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="toAttribute" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="pivotOrigin" type="{http://lsc-project.org/XSD/lsc-core-2.2.xsd}pivotOriginType" default="BOTH" /&gt;
     *     &lt;/extension&gt;
     *   &lt;/simpleContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Transformation {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "fromAttribute")
        protected String fromAttribute;
        @XmlAttribute(name = "toAttribute")
        protected String toAttribute;
        @XmlAttribute(name = "pivotOrigin")
        protected PivotOriginType pivotOrigin;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the fromAttribute property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFromAttribute() {
            return fromAttribute;
        }

        /**
         * Sets the value of the fromAttribute property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFromAttribute(String value) {
            this.fromAttribute = value;
        }

        /**
         * Gets the value of the toAttribute property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getToAttribute() {
            return toAttribute;
        }

        /**
         * Sets the value of the toAttribute property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setToAttribute(String value) {
            this.toAttribute = value;
        }

        /**
         * Gets the value of the pivotOrigin property.
         * 
         * @return
         *     possible object is
         *     {@link PivotOriginType }
         *     
         */
        public PivotOriginType getPivotOrigin() {
            if (pivotOrigin == null) {
                return PivotOriginType.BOTH;
            } else {
                return pivotOrigin;
            }
        }

        /**
         * Sets the value of the pivotOrigin property.
         * 
         * @param value
         *     allowed object is
         *     {@link PivotOriginType }
         *     
         */
        public void setPivotOrigin(PivotOriginType value) {
            this.pivotOrigin = value;
        }

    }

}
