//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.23 at 07:48:47 PM CET 
//


package org.lsc.configuration;

import java.util.ArrayList;
import java.util.List;
import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for pluginSyncOptionsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="pluginSyncOptionsType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://lsc-project.org/XSD/lsc-core-2.0.xsd}syncOptionsType">
 *       &lt;sequence>
 *         &lt;any maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="configurationClass" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="implementationClass" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "pluginSyncOptionsType", namespace = "http://lsc-project.org/XSD/lsc-core-2.0.xsd", propOrder = {
    "any"
})
@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-01-23T07:48:47+01:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
public class PluginSyncOptionsType
    extends SyncOptionsType
{

    @XmlAnyElement(lax = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-01-23T07:48:47+01:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    protected List<Object> any;
    @XmlAttribute
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-01-23T07:48:47+01:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    protected String configurationClass;
    @XmlAttribute
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-01-23T07:48:47+01:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    protected String implementationClass;

    /**
     * Gets the value of the any property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-01-23T07:48:47+01:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    public List<Object> getAny() {
        if (any == null) {
            any = new ArrayList<Object>();
        }
        return this.any;
    }

    /**
     * Gets the value of the configurationClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-01-23T07:48:47+01:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    public String getConfigurationClass() {
        return configurationClass;
    }

    /**
     * Sets the value of the configurationClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-01-23T07:48:47+01:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    public void setConfigurationClass(String value) {
        this.configurationClass = value;
    }

    /**
     * Gets the value of the implementationClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-01-23T07:48:47+01:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    public String getImplementationClass() {
        return implementationClass;
    }

    /**
     * Sets the value of the implementationClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-01-23T07:48:47+01:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    public void setImplementationClass(String value) {
        this.implementationClass = value;
    }

}
