//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.22 at 01:41:58 PM CET 
//


package org.lsc.configuration;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for saslQopType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="saslQopType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="auth"/>
 *     &lt;enumeration value="auth-int"/>
 *     &lt;enumeration value="auth-conf"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "saslQopType")
@XmlEnum
public enum SaslQopType {

    @XmlEnumValue("auth")
    AUTH("auth"),
    @XmlEnumValue("auth-int")
    AUTH_INT("auth-int"),
    @XmlEnumValue("auth-conf")
    AUTH_CONF("auth-conf");
    private final String value;

    SaslQopType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SaslQopType fromValue(String v) {
        for (SaslQopType c: SaslQopType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
