//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.24 at 10:00:27 AM CEST 
//


package org.lsc.configuration;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for saslQopType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="saslQopType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="auth"/&gt;
 *     &lt;enumeration value="auth-int"/&gt;
 *     &lt;enumeration value="auth-conf"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "saslQopType")
@XmlEnum
public enum SaslQopType {

    @XmlEnumValue("auth")
    AUTH("auth"),
    @XmlEnumValue("auth-int")
    AUTH_INT("auth-int"),
    @XmlEnumValue("auth-conf")
    AUTH_CONF("auth-conf");
    private final String value;

    SaslQopType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SaslQopType fromValue(String v) {
        for (SaslQopType c: SaslQopType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
